spring:
  datasource:
    url: jdbc:postgresql://bh-alexey:5432/pawnshop
    username: bh-alexey
    password: 
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
server:
  error:
    include-message: always
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    us.telran.pawnshop: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
